// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://twogxdshhwcyvxmvywjs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR3b2d4ZHNoaHdjeXZ4bXZ5d2pzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk2NDI0MTMsImV4cCI6MjA2NTIxODQxM30.ysdhjEUWzdbVxx_O8GM07PIDY59X-j9wjKfL-uwAzHQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);